Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

# Added a default URL path to my 'workblog' app.
urlpatterns = [
    path('', include('workblog.urls')),
    path('admin/', admin.site.urls),
]

workblog/urls.py
from django.urls import path

from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'workblog'
urlpatterns = [
    path('', views.index, name="index"),
    path('machine/<str:position>/', views.get_maschine_move, name='get_move'),
    path('project_sticker', views.project_sticker, name="project_sticker"),
    path('project_smetnaki', views.project_smetnaki, name="project_smetnaki"),
    path('project_personal_website', views.project_personal_website, name="project_personal_website"),
    path('blog', views.blog, name='blog'),
    path('resume', views.resume, name='resume'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workblog/models.py
from django.db import models

workblog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from workblog.models import *
from django.http import JsonResponse
from sticker import move_maschine

def project_sticker(request):
    return render(request, 'workblog/sticker.html', {})

def project_smetnaki(request):
    return render(request, 'workblog/smetnaki.html', {})

def project_personal_website(request):
    return render(request, 'workblog/personal_website.html', {})

def get_maschine_move(request, position):
    valid_position_format = [int(x) for x in str(position)]
    liszt = move_maschine('advanced', valid_position_format)
    move_data = {
        'row' : liszt[0],
        'number_of_cards' : liszt[1],
    }
    return JsonResponse(move_data)

def index(request):
    return render(request, 'workblog/index.html')

def blog(request):
    return render(request, 'workblog/detail.html', {})

def resume(request):
    return render(request, 'workblog/resume.html', {})

workblog/templates/workblog/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Rok Klančar</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'workblog/style.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Homepage"> 
        <meta name="keywords" content="programming, rok, rok klančar, klancar, work blog">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <!-- JQuery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <!-- Favicon -->
        <link href="{% static 'workblog/favicon.ico' %}" rel="shortcut icon" type="image/png" />
        <!-- Custom font -->
        <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
        {% block static_files %}{% endblock %}
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-98643439-2"></script>
	<script>
  		window.dataLayer = window.dataLayer || [];
 		function gtag(){dataLayer.push(arguments);}
  		gtag('js', new Date());
		
  		gtag('config', 'UA-98643439-2');
	</script>

    </head>
    <body>
        <!-- Navigation bar (left side) -->
        <nav>
            <ul>
                <!-- Orange button to homesite -->
                <li id="home"><a id="home_btn" href="{% url 'workblog:index' %}">Rok Klančar</a></li>
                <li><a href="{% url 'workblog:blog' %}">Work Blog</a></li>
                <li style="color: #138FB9;">Projects:</li>
                <li>
                    <ul>
                            <li><a href="{% url 'workblog:project_sticker' %}">sticker</a></li>
                            <li><a href="{% url 'workblog:project_personal_website' %}">rok-klancar.com</a></li>
                            <li><a href="{% url 'workblog:project_smetnaki' %}">smetnaki</a></li>
                    </ul>
                </li>
                <li><a href="https://drive.google.com/file/d/1DkWjX1JhiVdwXMJFEwRSnQN1etwtJ2XK/view?usp=sharing" target="_blank">Resume</a></li>
            </ul>
        </nav>
        <!-- Content (right side) -->
        <main>
            {% block content %}
            {% endblock %}
        </main>
    </body>
</html>

workblog/templates/workblog/detail.html
{% extends 'workblog/base.html' %}

{% load static %}
{% block static_files %}
<link rel="stylesheet" type="text/css" href="{% static 'workblog/code-style.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Ubuntu+Mono&display=swap" rel="stylesheet"> 
{% endblock %}

{% block content %}
<div class="article" id="15-october">
    <div class="article-title">
        <h2><a href="https://www.codewars.com/kata/5263c6999e0f40dee200059d">The Observed PIN</a></h2>
        <h3>15th of October</h3>
    </div>
    <br>
    <h4>Description</h4>
    <div class="description">
        <p>Alright, detective, one of our colleagues successfully observed our target person, Robby the robber.
        We followed him to a secret warehouse, where we assume to find all the stolen stuff. 
        The door to this warehouse is secured by an electronic combination lock. 
        Unfortunately our spy isn't sure about the PIN he saw, when Robby entered it.</p>
        <br>
        <p>
            The keypad has the following layout:
        </p>
        <pre class="unmarked">
            ┌───┬───┬───┐
            │ 1  │ 2 │ 3  │
            ├───┼───┼───┤
            │ 4  │ 5 │ 6  │
            ├───┼───┼───┤
            │ 7  │ 8 │ 9  │
            └───┼───┼───┘
                 │ 0  │
                 └───┘
        </pre>
    </div>
    <h4 class="sol">Solution</h4>
    <div class="solution">
        <pre>
    def <span class="function-name">get_pins</span>(observed):

    possibilities = {
        '1': {'1', '2', '4'},
        '2': {'1', '2', '3', '5'},
        '3': {'3', '2', '6'},
        '4': {'1', '4', '5', '7'},
        '5': {'2' ,'4' ,'5' ,'6' ,'8'},
        '6': {'3' ,'5' ,'6' ,'9'},
        '7': {'4' ,'7' ,'8'},
        '8': {'5' ,'7' ,'8' ,'9' ,'0'}, 
        '9': {'6' ,'8' ,'9'},
        '0': {'8' ,'0'}
    }
    
    return_list = ['']
    <span class="keyword">for</span> number <span class="keyword">in</span> observed:
        combinations = return_list
        return_list = []
        <span class="keyword">for</span> possibility <span class="keyword">in</span> possibilities[number]:
            <span class="keyword">for</span> combination <span class="keyword">in</span> combinations:
                return_list.<span class="function-name">append</span>(combination + possibility)

    <span class="keyword">return</span> return_list
        </pre>
    </div>
</div>
<div class="additional">
    <p>
        Thanks to my friend <a href="https://github.com/golobluka/The-observed-pin/blob/main/pin.py">Luka</a> again for giving me proper mathematical insight and help.
    </p>
</div>
<br>
<hr>
<br>
<div class="article" id="13-october">
    <div class="article-title">
        <h2><a href="https://www.codewars.com/kata/52597aa56021e91c93000cb0">Moving Zeroes To The End</a></h2>
        <h3>13th of October</h3>
    </div>
    <br>
    <h4>Description</h4>
    <div class="description">
        <p>Write an algorithm that takes an array and moves all of the zeros to the end, preserving the order of the other elements.</p>
        <pre class="unmarked">
moveZeros([false,1,0,1,2,0,1,3,"a"]) // returns[false,1,1,2,1,3,"a",0,0]
        </pre>
    </div>
    <h4 class="sol">Solution</h4>
    <div class="solution">
        <pre>
    def <span class="function-name">move_zeroes</span>(array):   
        return_array = []
        zeroes = []
        <span class="keyword">for</span> index, element <span class="keyword">in</span> <span class="function-name">enumerate</span>(array):
        <span class="keyword">if</span> (element == 0) <span class="keyword">and</span> element <span class="keyword">is</span> <span class="keyword">not</span> False:
                zeroes.<span class="function-name">append</span>(0)
            <span class="keyword">else</span>:
                return_array.<span class="function-name">append</span>(element)
        return_array.<span class="function-name">extend</span>(zeroes)
        <span class="keyword">return</span> return_array
        </pre>
    </div>
</div>
<br>
<hr>
<br>
    <div class="article" id="3-october">
        <div class="article-title">
            <h2><a href="https://www.codewars.com/kata/521c2db8ddc89b9b7a0000c1/discuss">Snail kata</a></h2>
            <h3>3rd of October</h3>
        </div>
        <br>
        <h4>Description</h4>
        <div class="description">
            <p>Given an n x n array, return the array elements arranged from outermost elements to the middle element, traveling clockwise.</p>
            <pre class="unmarked">
                array = [[1,2,3],
                         [4,5,6],
                         [7,8,9]]
                snail(array) #=> [1,2,3,6,9,8,7,4,5]
            </pre>
            <p>For better understanding, please follow the numbers of the next array consecutively:</p>
            <pre class="unmarked">
                array = [[1,2,3],
                         [8,9,4],
                         [7,6,5]]
                snail(array) #=> [1,2,3,4,5,6,7,8,9]
            </pre>
            <p>This image will illustrate things more clearly:</p>
            <img src="{% static 'workblog/tools_i_use/snail.png' %}" alt="">
            <p>
                NOTE: The idea is not sort the elements from the lowest value to the highest; the idea is to traverse the 2-d array in a clockwise snailshell pattern.
                <br>
                NOTE 2: The 0x0 (empty matrix) is represented as en empty array inside an array [[]].
            </p>
        </div>
        <h4 class="sol">Solution</h4>
        <div class="solution">
            <pre>
    def <span class="function-name">snail</span>(input_data):
        output_list = []

        <span class="keyword">try</span>:
            <span class="keyword">while</span> True:
                <span class="comment"># Append all elements of first list</span>
                <span class="keyword">for</span> element <span class="keyword">in</span> input_data[0]:
                    output_list.<span class="function-name">append</span>(element)
                <span class="comment"># Remove first list</span>
                input_data.<span class="function-name">pop</span>(0)

                <span class="comment"># Append last values of all lists
                # that remain, but the last one</span>
                <span class="keyword">for</span> list <span class="keyword">in</span> input_data:
                    <span class="keyword">if</span> list != input_data[-1]:
                        output_list.<span class="function-name">append</span>(list.<span class="function-name">pop</span>())
                
                <span class="comment"># Reverse the last list and append it</span>
                input_data[-1].<span class="function-name">reverse</span>()
                <span class="keyword">for</span> element <span class="keyword">in</span> input_data[-1]:
                    output_list.<span class="function-name">append</span>(element)
                input_data.<span class="function-name">remove</span>(input_data[-1])
                
                <span class="comment"># Append the first values of lists that 
                # remain, but reverse the lists first</span>
                input_data.<span class="function-name">reverse</span>()
                <span class="keyword">for</span> list <span class="keyword">in</span> input_data:
                    output_list.<span class="function-name">append</span>(list[0])
                    list.<span class="function-name">remove</span>(list[0])
                input_data.<span class="function-name">reverse</span>()
            
                <span class="comment"># Repeat untill the index is empty
                # at any step</span>
        
                <span class="keyword">except</span>:
        <span class="keyword">return</span> output_list
            </pre>
        </div>
        <div class="additional">
            <p>
                This exercise gave me somethin to think about. I've made a <a href="https://www.youtube.com/watch?v=-BOOzjcFq-0&t=1s">video</a> where I explain the exercise, go through
                my solution, and then debug it.
            </p>
        </div>
    </div>
    <hr>
{% endblock %}

workblog/templates/workblog/index.html
{% extends 'workblog/base.html' %}

{% load static %}
{% block content %}
            <article id="disclaimer">
                <div class="left-side">
                    <img class="rok" src="{% static 'workblog/tools_i_use/rok.jpg' %}" alt="">
                    <br>
                </div>
                <div class="right-side">
                <p>
                Hi! <br> My name is Rok and I am a self taught programmer
                <br><br>
                I do everything - from design to deployment 
                <br>
                (unless stated otherwise)
                <br>
                Working on a Xubuntu 18
                </p>
                <br>
                <p>
                    <a href="https://github.com/HyoMiYing" target="_blank">github</a> - HyoMiYing
                </p>
                <br>
                <div class="most-frequently-used-tools">
                    <h2>Most frequently programming in:</h2>
                    <ul>
                        <li class="list-item"><img src="{% static 'workblog/tools_i_use/python-original.jpg' %}" alt=""><span>Python</span></li>
                        <li class="list-item"><img src="{% static 'workblog/tools_i_use/javascript-original.jpg' %}" alt=""><span>JavaScript</span></li>
                        <li><br></li>
                        <h2>Favourite framework:</h2>
                        <li class="list-item"><img src="{% static 'workblog/tools_i_use/django-original.jpg' %}" alt=""><span>Django</span></li>
                    </ul>
                        </div>
            </article>
                    <br>
                    <br>
                    <div id="center">
                        <div id="game-ui">
                            <h2 id="game-title"><b>Sticker Game</b></h2>
                            <p id="game-subtitle">Whoever picks up the last card, looses.</p>
                            <form id='main-form'>
                            </form>
                            <div id="id-error">Please select at least one card</div>
                            <button id="submit-button">Make a move</button>
                        </div>
                        <br>
                        <br>
                        <br>
                        <br>
                        <p class="email">
                            You can reach me at <strong style="font-weight: 700;">rklancar@gmail.com</strong>.
                        </p>
                        <script src="{% static 'workblog/app.js' %}"></script>
                    </div>
{% endblock %}

workblog/templates/workblog/personal_website.html
{% extends 'workblog/base.html' %}
        
{% load static %}
{% block static_files %}
    <link rel="stylesheet" href="{% static 'workblog/sticker.css' %}">
{% endblock %}
{% block content %}
<div class="project">
    <h1><b>rok-klancar.com</b></h1>
    <br>
    <p><i>My personal website</i></p>
    <ol style="list-style-type: none !important;">
        <li><a href="/">Website</a></li>
        <li><a href="https://github.com/HyoMiYing/2020personal-website">GitHub</a></li>
    </ol>
    <br>
    <h2>Properties</h2>
    <br>
    <ul>
        <li>First (usable) project</li>
        <li>Done right after learning through the Django tutorial</li>
        <li>Basic functionality is to represent oneself</li>
        <li>Modified seveal times</li>
        <li>Spending lots of time on a project: coming back to it, changing it, improving it</li>
    </ul>
    <br>
    <br>
    <h2>Story</h2>
    <p>
        Rok has just finished the official <a href="https://www.djangoproject.com/">Django tutorial</a>, and had decided
        to finally put his <b>coding skills to good use</b>.
    </p>
    <p>
        He always wanted a nice personal website, but didn't like the websites made using wordpress. He had <b>designed it by
            himself</b>, taking example from websites on the internet that he liked.
    </p>
    <p>
        It was also the first time he <b>deployed</b> a website (first it was running on Heroku, but now it's on Digital Ocean's droplet).
    </p>
    <p>
        The website has been (since april 2019) <b>changed many times</b> (at least 3 major reworks). This gave Rok a nice refernce of working on a project for long
        periods of time.
        That means a lot of things: Coming back to see, that you don't understand what a specific piece of code does. Or <b>learning to
        work with version control</b> software for not just storing your data.
        Sometimes you need to retieve a file, or read the log to see when has something been done, or make a new branch to test something out.
    </p>
</div>
{% endblock %}

workblog/templates/workblog/projects.html
{% extends 'workblog/base.html' %}

{% block content %}
    {% load static %}
    {% if projects %}
    {% for project in projects %}
        <article>
            <!-- In-Depth info will be available in github README.md -->
            <div class="project-box">
                <div class="first-row">
                    <div class="title">
                        <h2>{{ project.title }}</h3>
                    </div>
                    <div class="icon">
                        <!-- <img src="{% static 'workblog/smetnaki-favicon.png' %}" alt=""> -->
                    </div>
                </div>
                <div class="second-row">
                    <div class="links">
                        <a class="link github-link" href="{{ project.github_url }}" target="_blank">
                            GitHub
                        </a>
                        <a class="link site-link" href="{{ project.site_url }}" target="_blank">
                            Live site
                        </a>
                    </div>
                </div>
                <div class="third-row">
                    <div class="description">
                        <p>{{ project.description }}</p>
                    </div>
                    <div class="built-with-icon">
                        <img src="{{ project.bulit_with_icon.url }}" alt="Icon that indicates what has thhis project been built with">
                    </div>
                </div>
            </div>
            </article>
            <hr class="projecthr">
    {% endfor %}
    {% else %}
        <article id="disclaimer">
            <p>
                No projects yet to show.
            </p>
        </article>
        {% endif %}

        {% endblock %}

workblog/templates/workblog/resume.html
<iframe src="https://drive.google.com/file/d/1DkWjX1JhiVdwXMJFEwRSnQN1etwtJ2XK/preview" width="640" height="480"></iframe>

<a href="https://docs.google.com/uc?export=download&id=1DkWjX1JhiVdwXMJFEwRSnQN1etwtJ2XK">
Direct Download</a>

workblog/templates/workblog/smetnaki.html
{% extends 'workblog/base.html' %}
        
{% load static %}
{% block static_files %}
    <link rel="stylesheet" href="{% static 'workblog/sticker.css' %}">
{% endblock %}
{% block content %}
<div class="project">
    <h1><b>Smetnaki website</b></h1>
    <br>
    <p><i>My band's calling card</i></p>
    <ol style="list-style-type: none !important;">
        <li><a href="https://www.smetnaki.si">Website</a></li>
        <li><a href="https://github.com/HyoMiYing/smetnaki">GitHub</a></li>
    </ol>
    <br>
    <h2>Properties</h2>
    <br>
    <ul>
        <li>Finished in less than a week</li>
        <li>Heavy use of <a href="https://www.figma.com/">Figma</a> for design</li>
        <li>Integration of internationalization and localization, so everyone can understand</li>
        <li>Easy to add upcoming concerts</li>
    </ul>
    <br>
    <br>
    <h2>Story</h2>
    <p>
        Smetnaki band had presence only on social networks but it didn't have its own website. 
    </p>
    <p>
        When saxophone player's father made a <b>cool design for a concert poster</b>, Rok was inspired
        by it and created the website.
    </p>
    <img src="{% static 'workblog/tools_i_use/smetnaki_page.png' %}" alt="Image from the smetnaki websites's landing page">
    <p>
        Rok started with designing the UI of the website in Figma. That is also how he spent
        the majority of the time on the project.
    </p>
    <p>
        Previously he had already made a project in Django, where he had to use <b>localization and internationalization</b>
        so the Smetnaki was a nice example where this knowledge was proven usable.
    </p>
</div>
{% endblock %}

workblog/templates/workblog/sticker.html
{% extends 'workblog/base.html' %}
        
{% load static %}
{% block static_files %}
    <link rel="stylesheet" href="{% static 'workblog/sticker.css' %}">
{% endblock %}
{% block content %}
<div class="project">
    <h1><b>Sticker Project</b></h1>
    <br>
    <p><i>It was very confusing to dedicate so much work for such a useless project</i></p>
    <ol style="list-style-type: none !important;">
        <li><a href="/">Website</a></li>
        <li><a href="https://github.com/HyoMiYing/web-sticker">GitHub</a></li>
    </ol>
    <br>
    <h2>Properties</h2>
    <br>
    <ul>
        <li>Made in cooperation with my mathematician friend</li>
        <li>Django framework</li>
        <li>Elements of TDD (Functional tests)</li>
        <li>Deployment is automatized with <a href="http://www.fabfile.org/">Fabric</a></li>
        <li>There is no database, as there is no need for one</li>
        <li>Styling is minimal</li>
        <li>UI/UX is coded with vanilla JavaScript</li>
        <li>AJAX enables 2 player game</li>
    </ul>
    <br>
    <br>
    <h2>Story</h2>
    <p>
        Rok has just finished reading the book <a href="https://www.obeythetestinggoat.com/">Test-Driven Development with Python</a> by Harry J.W. Percival. The book was very
        helpful and beginner-friendly, as it provided clear instructions and also introduced some common programming tools and techniques 
        (sorted by usefulness):
    </p>
    <img src="{% static 'workblog/tools_i_use/tdd_book.jpg' %}" alt="Rok holding the Test Driven Development with Python book">
    <ul id="book-list">
        <li>Automating deployment with <a href="http://www.fabfile.org/">Fabric</a></li>
        <li>Controlling web browser with <a href="https://selenium-python.readthedocs.io/index.html">Selenium</a></li>
        <li>Testing Python code</li>
        <li>Integrating git into workflow</li>
        <li>Testing JavaScript code (with <a href="https://qunitjs.com/">QUnit</a>)</li>
        <li><a href="http://agiledictionary.com/209/spike/">Spiking</a></li>
        <li>'Staging server' and 'Production server'</li>
    </ul>
    <p>
        Around that time Luka, Rok's friend was visiting. He had <b>something to show</b>. Simple game, nicknamed 'Sticker',
        which 'is interesting only for the first 5 rounds'.
        Rok then had the idea to <b>turn the game into a web game</b> and Luka agreed: one would make the Sticker game module, called <code>sticker.py</code>
        and the other would make a Django web project, which would use <code>sticker.py</code>.
    </p>
    <p>
        Rok already had <b>experience with delegating programming tasks and writing specifications</b>. 
        They sat down and decribed data that will enter and exit from Luka's module.
    </p>
    <img id="scheme" src="{% static 'workblog/tools_i_use/program_scheme.png' %}" alt="Scheme of modules in the project">
    <p>
        After that, each of them went to work. Rok <b>attempted to code the whole project using TDD</b>. It didn't matter if there was no Sticker module yet, as he could always just use 
        mock data. So he tried to do that for 2 weeks. Following the TDD methodology was very hard whenever the project was different from the project
        done in the book. Writing the unit tests was the hardest part, but Rok kept at it, as he desired to apply the newly learned skills. He started to learn from
        other resources.
        He spent several days studying other material on TDD (Book by Kent Beck, <a href="https://www.youtube.com/watch?v=AoIfc5NwRks">uncle Bob's video</a>,
        <a href="https://www.youtube.com/watch?v=EZ05e7EMOLM">Ian Cooper's talk</a>, etc.)
    </p>
    <p>
        But after some time Rok had to admit the defeat. He was just <b>too unexperienced</b> to move forward with TDD.
        Out of frustration, he started the whole project from the beginning, but still keeping some things he did understand (Functional tests, deployment with Fabric).
        Rok worked for 3 - 6 hours per day (but not on weekends), and after 2 weeks the project was deployed.
    </p>
    <p>
        However, the project had a major flaw. 2 player game mode was <b>highly unpractical</b>, as the players would have to meet in another service, 
        share the game URL, and on top of that both be online at the same time. Rok decided to improve this. He was brainstorming, but the plans changed 
        every day. It was very confusing to dedicate so much work for such a useless project.
    </p>
    <p>
        Finally, Rok finished the project, despite its disadvantages. He showed it to a senior programmer who said:
          <i>'Why are you making AJAX call every 0.5 seconds, when you can just use the web sockets?'</i>.
    </p>
    <p>
        Rok did some research and found out, that <a href="https://channels.readthedocs.io/en/latest/">Django channels</a> is officialy
        <a href="https://www.djangoproject.com/weblog/2016/sep/09/channels-adopted-official-django-project/">part of the 
        Django project</a> and it enables the use of web sockets. He began studying the technology with the
        goal to apply it to the Sticker project. He realized, that the <b>use of web sockets would make his project much simpler and better to use!</b>
    </p>
    <p>
        But right after setting up and starting to mess with the Channels, Rok
        had to make a break from programming, since he had to study for his Matura exam, as it
        included 4 years worth of subject matter for 5 different subjects.
    </p>
    <p>
        After returning to programming, he used the AI part of Luka's module and written some JavaScript code.
        That is how the Sticker game on the <a href="https://www.rok-klancar.com#main-form">homepage of this website</a> got to be.
        <i>It took one day to code it</i> and Rok couldn't wrap his head around the fact, that
        he needed 1 month before to do basically the same thing.
    </p>
    <p>
        The game on homepage runs entirely vanilla JS. There is only some JQuery code that retrieves information from a specific view about
        the next 'machine move'.
    </p>
</div>
{% endblock %}